config/routes.rb
RedmineApp::Application.routes.draw do
	resources :indicators
	resources :kpi_patterns

	resources :kpi_mark_offers do
		collection do
			get 'mark_offers/:mark_id', :action => 'mark_offers'
			end
		
		end
	#resources :kpi_calc_periods
	#match 'kpi', :controller => 'kpi', :action => 'index', :via => [:get]
	#match 'kpi/marks', :controller => 'kpi', :action => 'marks', :via => [:get]
	resources :kpi do
		collection do
			#get '/', :action => 'index'
			#get 'marks'
			#get 'marks/:date', :action => 'marks'
			get 'effectiveness'
			#get 'effectiveness/:date', :action => 'effectiveness'
			get 'effectiveness/:user_id', :action => 'effectiveness'
			get 'effectiveness/:date/:user_id', :action => 'effectiveness'

		end
	end

	match 'indicators/:copy_from/copy', :to => 'indicators#new'
	#match 'kpi_patterns/:id/users', :controller => 'kpi_patterns', :action => 'add_users', :id => /\d+/, :via => :post, :as => 'kpi_patters_users'
	#match 'kpi_patterns/:id/users/:user_id', :controller => 'kpi_patterns', :action => 'remove_user', :id => /\d+/, :via => :delete, :as => 'kpi_pattern_user'
	#match 'kpi_patterns/:id/indicators', :controller => 'kpi_patterns', :action => 'add_indicators', :id => /\d+/, :via => :post, :as => 'kpi_patters_indicators'
	#match 'kpi_patterns/:id/update_indicators', :controller => 'kpi_patterns', :action => 'update_indicators', :id => /\d+/, :via => :post, :as => 'kpi_patterns_indicators_edit'
	#match 'kpi_patterns/:id/indicators/:indicator_id', :controller => 'kpi_patterns', :action => 'remove_indicator', :id => /\d+/, :via => :delete, :as => 'kpi_pattern_indicator'
	match 'kpi_patterns/:copy_from/copy', :to => 'kpi_patterns#edit'


	resources :kpi_user_surcharges do
	    member do
	    	get 'show_surcharges', :action => 'show_surcharges'
	    	post 'add_surcharge', :action => 'add_surcharge'
	    end
	end

	resources :kpi_applied_reports do
		collection do
			get 'show', :action => 'show'
			get 'apply/:date/:department_id', :action => 'apply'
			get 'audit/:date/:department_id', :action => 'audit'
			get 'cancel/:date/:department_id', :action => 'cancel'
			get 'cancel_audit/:date/:department_id', :action => 'cancel_audit'
		end

	end

	resources :kpi_period_users do
	    member do
	    	get 'edit_hours', :action => 'edit_hours'
	    	get 'edit_base_salary', :action => 'edit_base_salary'
	    	get 'close_message', :action => 'close_message'
	    	get 'edit_jobprise', :action => 'edit_jobprise'
	    	post 'update_base_salary', :action => 'update_base_salary'
	    	post 'update_jobprise', :action => 'update_jobprise'
	    	post 'update_hours', :action => 'update_hours'
	    	get 'close'
	    	get 'reopen'
	    	get 'reopen_message'
	    end
	end

	resources :kpi_marks do
	    member do
	      get 'edit_plan', :action => 'edit_plan'
	      post 'update_plan', :action => 'update_plan'
	      get 'edit_fact', :action => 'edit_fact'
	      post 'update_fact', :action => 'update_fact'
	      get 'show_info', :action => 'show_info'
	      get 'disable', :action => 'disable'
	      get 'enable', :action => 'enable'
	    end

	    collection do
				#get '/:date', :action => 'index'
	    	get 'user/:user_id', :action => 'user_marks'
	    	post 'update_user_marks/:user_id', :action => 'update_user_marks'
	    	get 'show_for_offer', :action => 'show_for_offer'
	    	#get 'user/:user'
	    end
	end

	resources :kpi_patterns do
	    member do
	      post 'add_users', :action =>'add_users'
	      delete 'remove_user/:user_id', :action => 'remove_user'
	      post 'add_indicators', :action => 'add_indicators'
	      post 'update_indicators', :action => 'update_indicators'
	      delete 'remove_indicator/:indicator_id', :action => 'remove_indicator'
	      get 'autocomplete_for_user'
	      get 'autocomplete_for_indicator'
	    end
	end

	resources :kpi_imported_values do
	    collection do
	      post 'update_values'
	      get 'edit_values'
	      get 'permission_titles', :action => 'permission_titles'
	    end
	end

	resources :kpi_calc_periods do
		collection do
		#get '/:date', :action => 'index'
	    end

	    member do
	   	  # get 'close_for_user/:user_id', :action => 'close_for_user'
	   	  # get 'reopen_for_user/:user_id', :action => 'reopen_for_user'
	      post 'add_inspectors'
	      post 'add_users', :as => 'add_users'
	      get 'autocomplete_for_user'
	      get 'autocomplete_for_applied_user'
	      get 'show_warning_message'
	      get 'activate'
	      get 'close'
	      delete 'remove_inspector/:indicator_inspector_id', :action => 'remove_inspector', :as => 'remove_inspector'
	      delete 'remove_user/:period_user_id', :action => 'remove_user', :as => 'remove_user'
	      post 'update_inspectors', :action => 'update_inspectors', :as => 'update_inspectors'
	      post 'update_plans', :action => 'update_plans', :as => 'update_plans'
	    end
	end

end


# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

app/models/kpi_pattern.rb
class KpiPattern < ActiveRecord::Base
	validates_presence_of :name
	validates_uniqueness_of :name

	has_many :kpi_pattern_users
	has_many :users, :through => :kpi_pattern_users
	has_many :kpi_pattern_indicators, :dependent => :destroy
	has_many :indicators, :through => :kpi_pattern_indicators
	has_many :kpi_calc_periods
	has_many :kpi_pattern_categories, :dependent => :destroy

	def integrity?
		categories_integrity? && indicators_integrity?
	end 

	def indicators_integrity?
		! KpiPatternIndicator.where(:kpi_pattern_id => id).joins(:indicator).select("sum(#{KpiPatternIndicator.table_name}.percent) AS weight").group("kpi_category_id").having("sum(#{KpiPatternIndicator.table_name}.percent)!=100 OR sum(#{KpiPatternIndicator.table_name}.percent) IS NULL").map{|e| e }.any?
	end

	def copy_to(pattern)
		copy_users_to(pattern)
		copy_categories_to(pattern)
		copy_indicators_to(pattern)
	end

	def copy_users_to(pattern)
		kpi_pattern_users.each do |u|
			KpiPatternUser.create(:kpi_pattern_id => pattern.id, :user_id => u.user_id)
		end		
	end

	def copy_indicators_to(pattern)
		kpi_pattern_indicators.each do |i|
			KpiPatternIndicator.create(:kpi_pattern_id => pattern.id, :indicator_id => i.indicator_id, :percent => i.percent)
		end		
	end

	def copy_categories_to(pattern)
		kpi_pattern_categories.each do |c|
			KpiPatternCategory.create(:kpi_pattern_id => pattern.id, :kpi_category_id => c.kpi_category_id, :percent => c.percent)
		end		
	end

	def categories_integrity?
		if kpi_pattern_categories.sum("percent")==100
			true
		else
			false
		end		
	end
end

app/controllers/kpi_patterns_controller.rb

class KpiPatternsController < ApplicationController
	before_filter :authorized_globaly?

	before_filter :find_patterns, :only => [:index]
	before_filter :get_pattern, :except => [:new, :create, :index]
	before_filter :find_category_weights, :except => [:new, :create, :index, :add_indicators]
	#before_filter :get_integrity_warnings, :only => [:update_indicators, :add_indicators, :remove_indicator, :edit]

	helper :kpi
	include KpiHelper

	def index
		
	end

	def new
		if !params[:copy_from].nil?
			source_pattern=KpiPattern.find(params[:copy_from])
		    attributes = source_pattern.attributes.dup.except('id')
		    @pattern = KpiPattern.new(attributes)
		else
		    @pattern = KpiPattern.new
		end
	end

	def edit
		#@pattern ||= KpiPattern.find(params[:id])
		get_integrity_warnings
	end

	def update
	    #@pattern = KpiPattern.find(params[:id])
	    if request.put? and @pattern.update_attributes(params[:kpi_pattern])
	      flash[:notice] = l(:notice_successful_update)
	      redirect_to(edit_kpi_pattern_path(@pattern))
	      return
	    end
	    render :action => 'edit'
	end

	def create
	@pattern = KpiPattern.new(params[:kpi_pattern])
	    if request.post? and @pattern.save
		   	flash[:notice] = l(:notice_successful_create)

		   	if not params[:copy_from].nil?
		   		source_pattern = KpiPattern.find(params[:copy_from])
		   		source_pattern.copy_to @pattern
		   	end

		    redirect_to(edit_kpi_pattern_path(@pattern))
		else
		    render :action => 'new'

		end
    end

	def destroy
	    #@pattern = KpiPattern.find(params[:id])
	    #unless @tracker.issues.empty?
	    #  flash[:error] = l(:error_can_not_delete_tracker)
	    #else
	      @pattern.destroy
	    #end
	    redirect_to :action => 'index'
	end    

	def add_users
	    #@pattern = KpiPattern.find(params[:id])
	    @users = User.find_all_by_id(params[:user_ids])
	    @pattern.users << @users if request.post?
		respond_to do |format|
			 format.js { render 'users' }
		end
	end

	def remove_user
	    #@pattern = KpiPattern.find(params[:id])
	    @pattern.users.delete(User.find(params[:user_id])) if request.delete?
		respond_to do |format|
			 format.js { render 'users' }
		end
	end

	def add_indicators
	    #@pattern = KpiPattern.find(params[:id])
	    @indicators = Indicator.find_all_by_id(params[:indicator_ids])
	    @pattern.indicators << @indicators if request.post?
	    find_category_weights    
	    get_integrity_warnings
		respond_to do |format|
			 format.js { render 'indicators' }
		end

	end

	def update_indicators
		#@pattern = KpiPattern.find(params[:id])
		params[:percent].each{|k,v|
			kpi_pattern_undicator=KpiPatternIndicator.find(k)
			kpi_pattern_undicator.percent=v
			kpi_pattern_undicator.save
			kpi_pattern_undicator.errors.full_messages.each do |error_msg| 
			      @indicator_save_errors.push(error_msg)
			    end 			
			}
		params[:cat_percent].each{|k,v|
			#Rails.logger.debug("ssssssss____#{k}____#{@pattern.id}")
			pc=KpiPatternCategory.where(:kpi_category_id => k, :kpi_pattern_id => @pattern.id).first
			pc.percent=v
			pc.save
			}
		get_integrity_warnings

		respond_to do |format|
			 format.js { render 'indicators' }
		end
	end

	def remove_indicator
	    #@pattern = KpiPattern.find(params[:id])
	    #@pattern.indicators.delete(Indicator.find(params[:indicator_id])) if request.delete?
	    KpiPatternIndicator.find(params[:indicator_id]).destroy if request.delete?
	    get_integrity_warnings
		respond_to do |format|
			 format.js { render 'indicators' }
		end
	end


	def autocomplete_for_user
	    #@pattern = KpiPattern.find(params[:id])
	    @users = User.active.not_in_kpi_pattern(@pattern).like(params[:q]).all(:limit => 100)
	    render 'groups/autocomplete_for_user', :layout => false
	end

	def autocomplete_for_indicator
	    #@pattern = KpiPattern.find(params[:id])
	    @indicators = Indicator.not_in_kpi_pattern(@pattern).where("name like ?", "%#{params[:q]}%").limit(100)
	    render 'kpi_patterns/autocomplete_for_indicator', :layout => false
	end	

	private

	def get_pattern
		@indicator_save_errors=[]
		@kpi_warnings=[]
		@pattern = KpiPattern.find(params[:id])
	end 

	def get_integrity_warnings
		if(@pattern.integrity?)
			if ! @pattern.integrity
				@pattern.integrity=true
				@pattern.save
			end
		else
			@kpi_warnings.push('indicators_weight_sum_not_equal_100') 
			if @pattern.integrity
				@pattern.integrity=false
				@pattern.save
			end
		end
	end

	def find_patterns
	 	@patterns=KpiPattern.order(:name)
	end

	def find_category_weights
		@category_weights={}
		@pattern.kpi_pattern_categories.each{|e|
			@category_weights[e.kpi_category_id.to_s]=e.percent
			#Rails.logger.debug("ssssssss #{e.kpi_category_id.to_s} #{e.percent}")
			}
	end

end

app/helpers/kpi_patterns_helper.rb
module KpiPatternsHelper
  def kpi_patterns_settings_tabs
    tabs = [{:name => 'users', :partial => 'kpi_patterns/users', :label => :label_assigned_list},
    		{:name => 'indicators', :partial => 'kpi_patterns/indicators', :label => :label_kpi_indicators},
            {:name => 'general', :partial => 'kpi_patterns/general', :label => :label_general}
           
            ]
  end


  def indicators_check_box_tags(name, indicators)
    s = ''
    indicators.sort.each do |indicator|
      s << "<label>#{ check_box_tag name, indicator.id, false } #{h indicator}</label>\n"
    end
    s.html_safe
  end
end

app/views/kpi_patterns/_autocomplete_for_indicator.html.erb
asdfasd

app/views/kpi_patterns/_form.html.erb
<%= error_messages_for 'pattern' %>

<div class="h">
<div class="box tabular">

<%= hidden_field_tag 'copy_from', params[:copy_from] unless params[:copy_from].nil? %>

<p><%= f.text_field :name, :required => true, :label => l(:kpi_pattern_name_label), :style=>'width: 80%;' %></p>
<p>   <%= f.text_area :description,
                   :cols => 60,
                   :rows => (@pattern.description.blank? ? 10 : [[10, @pattern.description.length / 50].max, 70].min),
                   :class => 'wiki-edit',
                   :label => l(:kpi_description_label)%>
</p>
</div>
</div>

<div>
<%= submit_tag l(@pattern.new_record? ? :button_create : :button_save) %>
</div>

app/views/kpi_patterns/_general.html.erb
<%= labelled_form_for @pattern do |f| %>
<%= render :partial => 'kpi_patterns/form', :locals => { :f => f } %>
<% end %>

app/views/kpi_patterns/_indicators.html.erb
<% if @indicator_save_errors.any? %>
  <div id="errorExplanation">
  <ul>
<% @indicator_save_errors.each do |error| %>
  <li><%= h error %></li>
<% end %>
  </ul>
  </div>
<% end %>


<div class="splitcontentleft">
<% if @pattern.indicators.any? %>

  <%= form_for(@pattern, :remote => true, :url => {:controler => 'kpi_patterns', :action => 'update_indicators'},
               :html => {:method => :post}) do |f| %>
  <table class="list indicators">
    <thead><tr>
      <th><%= l(:indicator_label) %></th>
      <th style="width:5%"><%= l(:weight_label) %></th>
      <th style="width:5%"></th>
    </tr></thead>
    <tbody>
    <% last_category=nil %>
    <% color='' %>
    <% i=1 
       j=1000 %>
    <% @pattern.kpi_pattern_indicators.sort_by{|e| e.indicator.kpi_category.name.to_s+e.indicator.name.to_s}.each do |pattern_indicator| %>
      <% if last_category!=pattern_indicator.indicator.kpi_category %>
        <% last_category=pattern_indicator.indicator.kpi_category %>
        <% color=last_category.color %>
        <tr class="<%= color %>">
          <td><b><%= last_category.name %></b></td>
          <td class="weight"><input tabindex="<%= j %>" type="text" name="cat_percent[<%= h last_category.id %>]" value="<%= @category_weights[last_category.id.to_s] %>" /> </td>
          <td></td>
          <% j+=1 %>
        </tr>
      <% end %>
      <tr id="indicator-<%= pattern_indicator.indicator.id %>" class="<%= cycle 'odd', 'even' %> <%= color %>">
        <td class="indicator"><%= link_to h(pattern_indicator.indicator.name), edit_indicator_path(pattern_indicator.indicator) %></td>
        <td class="weight">
        <input type="text" tabindex="<%= i %>" name="percent[<%= h pattern_indicator.id %>]" value="<%= h pattern_indicator.percent %>" />
        </td>
        <td class="buttons">
            <%= delete_link({:controler => "kpi_patterns", :action => 'remove_indicator', :indicator_id => pattern_indicator.id}, {:method => :delete, :remote => true}) %>
        </td>
      </tr>
      
      <% i+=1 %>
    <% end %>
    </tbody>
  </table>

  <p><%= submit_tag l(:button_save) %></p>

  <% end %>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>
</div>

<div class="splitcontentright">
<% indicators = Indicator.not_in_kpi_pattern(@pattern).all(:limit => 100) %>
<% if indicators.any? %>
  <%= form_for(@pattern, :remote => true, :url => {:controler => 'kpi_patterns', :action => 'add_indicators'},
               :html => {:method => :post}) do |f| %>
    <fieldset><legend><%=l(:label_indicator_new)%></legend>
    <p><%= label_tag "indicators_search", l(:label_indicator_search) %><%= text_field_tag 'indicators_search', nil %></p>

    <%= javascript_tag "observeSearchfield('indicators_search', 'indicators', '#{ escape_javascript autocomplete_for_indicator_kpi_pattern_path(@pattern) }')" %>


    <div id="indicators">
      <%= indicators_check_box_tags 'indicator_ids[]', indicators %>
    </div>

    <p><%= submit_tag l(:button_add) %></p>
    </fieldset>
  <% end %>
<% end %>

</div>

app/views/kpi_patterns/_users.html.erb
<div class="splitcontentleft">
<% if @pattern.users.any? %>
  <table class="list users">
    <thead><tr>
      <th><%= l(:label_user) %></th>
      <th style="width:15%"></th>
    </tr></thead>
    <tbody>
    <% @pattern.users.sort.each do |user| %>
      <tr id="user-<%= user.id %>" class="<%= cycle 'odd', 'even' %>">
        <td class="user"><%= link_to_user user %></td>
        <td class="buttons">

        <%= delete_link({:controller => "kpi_patterns", :action => 'remove_user', :user_id => user.id}, {:method => :delete, :remote => true}) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>
</div>

<div class="splitcontentright">
<% users = User.active.not_in_kpi_pattern(@pattern).all(:limit => 100) %>
<% if users.any? %>
  <%= form_for(@pattern, :url => {:controller => "kpi_patterns", :action => "add_users"}, :html => {:method => :post, :remote => true}) do |f| %>
    <fieldset><legend><%=l(:label_user_new)%></legend>
    <p><%= label_tag "user_search", l(:label_user_search) %><%= text_field_tag 'user_search', nil %></p>

    <%= javascript_tag "observeSearchfield('user_search', 'users', '#{ escape_javascript autocomplete_for_user_kpi_pattern_path(@pattern) }')" %>

    <div id="users">
      <%= principals_check_box_tags 'user_ids[]', users %>
    </div>

    <p><%= submit_tag l(:button_add) %></p>
    </fieldset>
  <% end %>
<% end %>

</div>

app/views/kpi_patterns/_warnings.html.erb
<% if @kpi_warnings.any? %>
<div class="flash warning">
<% @kpi_warnings.each do |error| %>
	  <%= l(error) %>
<% end %>	
</div>
<% end %>

app/views/kpi_patterns/autocomplete_for_indicator.html.erb
<%= principals_check_box_tags 'indicator_ids[]', @indicators %>


app/views/kpi_patterns/edit.html.erb
<div id="kpi_pattern_warnings">
<%= render :partial => 'kpi/warnings' %> 
</div>

<div class="contextual">
<%= render :partial => 'kpi/kpi_common_links' %>
</div>

<h2><%=l(:label_kpi_patterns_edit)%></h2>

<%= render_tabs kpi_patterns_settings_tabs %>

<%= render :partial => 'kpi/sidebar' %>

app/views/kpi_patterns/index.html.erb
<div class="contextual">
<%= render :partial => 'kpi/kpi_common_links' %>
</div>

<h2><%= l(:label_kpi_patterns) %></h2>

<% if @patterns.any? %>

<table class="list patterns">
<thead>
	<tr>
	<th><%= l(:label_kpi_indicators) %></th>
	<th></th>
	</tr>
</thead>

<tbody>
<% @patterns.each do |pattern| %>
	<tr class="<%= 'not_integrity' if not pattern.integrity %>">
		<td><%= link_to h(pattern.name), edit_kpi_pattern_path(pattern) %></td>
		<td class="buttons">
			<%= link_to(l(:button_copy), { :controller => 'kpi_patterns', :action => 'new', :copy_from => pattern }, :class => 'icon icon-copy') %>

		    <%= link_to(l(:button_delete), kpi_pattern_path(pattern),
		                                   :method => :delete,
		                                   :confirm => l(:text_are_you_sure),
		                                   :class => 'icon icon-del') %>
		</td>
	</tr>
<% end %>
</tbody>

</table>

<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<%= render :partial => 'kpi/sidebar' %>

app/views/kpi_patterns/indicators.js.erb
$('#tab-content-indicators').html('<%= escape_javascript(render :partial => 'kpi_patterns/indicators') %>');
$('#kpi_pattern_warnings').html('<%= escape_javascript(render :partial => 'kpi_patterns/warnings') %>');

<% unless @indicators.nil? %>
    <% @indicators.each do |indicator| %>
        $('#indicator-<%= indicator.id %>').effect("highlight");
    <% end %>
<% end %>

app/views/kpi_patterns/new.html.erb
<h2><%=l(:label_kpi_patterns_new)%></h2>

<%= labelled_form_for @pattern do |f| %>
<%= render :partial => 'kpi_patterns/form', :locals => { :f => f } %>
<% end %>

<%= render :partial => 'kpi/sidebar' %>

app/views/kpi_patterns/users.js.erb
$('#tab-content-users').html('<%= escape_javascript(render :partial => 'kpi_patterns/users') %>');

<% unless @users.nil? %>
    <% @users.each do |user| %>
        $('#user-<%= user.id %>').effect("highlight");
    <% end %>
<% end %>