config/routes.rb
RedmineApp::Application.routes.draw do
	resources :indicators
	resources :kpi_patterns

	resources :kpi_mark_offers do
		collection do
			get 'mark_offers/:mark_id', :action => 'mark_offers'
			end
		
		end
	#resources :kpi_calc_periods
	#match 'kpi', :controller => 'kpi', :action => 'index', :via => [:get]
	#match 'kpi/marks', :controller => 'kpi', :action => 'marks', :via => [:get]
	resources :kpi do
		collection do
			#get '/', :action => 'index'
			#get 'marks'
			#get 'marks/:date', :action => 'marks'
			get 'effectiveness'
			#get 'effectiveness/:date', :action => 'effectiveness'
			get 'effectiveness/:user_id', :action => 'effectiveness'
			get 'effectiveness/:date/:user_id', :action => 'effectiveness'

		end
	end

	match 'indicators/:copy_from/copy', :to => 'indicators#new'
	#match 'kpi_patterns/:id/users', :controller => 'kpi_patterns', :action => 'add_users', :id => /\d+/, :via => :post, :as => 'kpi_patters_users'
	#match 'kpi_patterns/:id/users/:user_id', :controller => 'kpi_patterns', :action => 'remove_user', :id => /\d+/, :via => :delete, :as => 'kpi_pattern_user'
	#match 'kpi_patterns/:id/indicators', :controller => 'kpi_patterns', :action => 'add_indicators', :id => /\d+/, :via => :post, :as => 'kpi_patters_indicators'
	#match 'kpi_patterns/:id/update_indicators', :controller => 'kpi_patterns', :action => 'update_indicators', :id => /\d+/, :via => :post, :as => 'kpi_patterns_indicators_edit'
	#match 'kpi_patterns/:id/indicators/:indicator_id', :controller => 'kpi_patterns', :action => 'remove_indicator', :id => /\d+/, :via => :delete, :as => 'kpi_pattern_indicator'
	match 'kpi_patterns/:copy_from/copy', :to => 'kpi_patterns#edit'


	resources :kpi_user_surcharges do
	    member do
	    	get 'show_surcharges', :action => 'show_surcharges'
	    	post 'add_surcharge', :action => 'add_surcharge'
	    end
	end

	resources :kpi_applied_reports do
		collection do
			get 'show', :action => 'show'
			get 'apply/:date/:department_id', :action => 'apply'
			get 'audit/:date/:department_id', :action => 'audit'
			get 'cancel/:date/:department_id', :action => 'cancel'
			get 'cancel_audit/:date/:department_id', :action => 'cancel_audit'
		end

	end

	resources :kpi_period_users do
	    member do
	    	get 'edit_hours', :action => 'edit_hours'
	    	get 'edit_base_salary', :action => 'edit_base_salary'
	    	get 'close_message', :action => 'close_message'
	    	get 'edit_jobprise', :action => 'edit_jobprise'
	    	post 'update_base_salary', :action => 'update_base_salary'
	    	post 'update_jobprise', :action => 'update_jobprise'
	    	post 'update_hours', :action => 'update_hours'
	    	get 'close'
	    	get 'reopen'
	    	get 'reopen_message'
	    end
	end

	resources :kpi_marks do
	    member do
	      get 'edit_plan', :action => 'edit_plan'
	      post 'update_plan', :action => 'update_plan'
	      get 'edit_fact', :action => 'edit_fact'
	      post 'update_fact', :action => 'update_fact'
	      get 'show_info', :action => 'show_info'
	      get 'disable', :action => 'disable'
	      get 'enable', :action => 'enable'
	    end

	    collection do
				#get '/:date', :action => 'index'
	    	get 'user/:user_id', :action => 'user_marks'
	    	post 'update_user_marks/:user_id', :action => 'update_user_marks'
	    	get 'show_for_offer', :action => 'show_for_offer'
	    	#get 'user/:user'
	    end
	end

	resources :kpi_patterns do
	    member do
	      post 'add_users', :action =>'add_users'
	      delete 'remove_user/:user_id', :action => 'remove_user'
	      post 'add_indicators', :action => 'add_indicators'
	      post 'update_indicators', :action => 'update_indicators'
	      delete 'remove_indicator/:indicator_id', :action => 'remove_indicator'
	      get 'autocomplete_for_user'
	      get 'autocomplete_for_indicator'
	    end
	end

	resources :kpi_imported_values do
	    collection do
	      post 'update_values'
	      get 'edit_values'
	      get 'permission_titles', :action => 'permission_titles'
	    end
	end

	resources :kpi_calc_periods do
		collection do
		#get '/:date', :action => 'index'
	    end

	    member do
	   	  # get 'close_for_user/:user_id', :action => 'close_for_user'
	   	  # get 'reopen_for_user/:user_id', :action => 'reopen_for_user'
	      post 'add_inspectors'
	      post 'add_users', :as => 'add_users'
	      get 'autocomplete_for_user'
	      get 'autocomplete_for_applied_user'
	      get 'show_warning_message'
	      get 'activate'
	      get 'close'
	      delete 'remove_inspector/:indicator_inspector_id', :action => 'remove_inspector', :as => 'remove_inspector'
	      delete 'remove_user/:period_user_id', :action => 'remove_user', :as => 'remove_user'
	      post 'update_inspectors', :action => 'update_inspectors', :as => 'update_inspectors'
	      post 'update_plans', :action => 'update_plans', :as => 'update_plans'
	    end
	end

end


# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

app/models/kpi_mark_offer.rb
class KpiMarkOffer < ActiveRecord::Base
  validates_presence_of :user_id, :author_id, :kpi_mark_id, :is_praise

  belongs_to :user
  belongs_to :author, :class_name => 'User', :foreign_key => 'author_id'

  belongs_to :kpi_mark
end

app/controllers/kpi_mark_offers_controller.rb
class KpiMarkOffersController < ApplicationController
  #before_filter get_marks_for_offer, :only => [:create]

  helper :kpi
  include KpiHelper

  def mark_offers
    @mark = KpiMark.find(params[:mark_id])
    render "mark_offers", :layout => false
  end

  def index
    @mark_offers = KpiMarkOffer.includes([:user, {:kpi_mark => {:kpi_period_indicator => :indicator}}]).where(:author_id => User.current.id).order("created_at DESC").limit(20)
  end

  def new
    @mark_offer = KpiMarkOffer.new
  end

  def edit
    @mark_offer = KpiMarkOffer.find(params[:id])
    get_marks_for_offer
  end

  def destroy
    @mark_offer = KpiMarkOffer.find(params[:id])
    @mark_offer.destroy
    if @mark_offer.errors.any?
      flash[:error] = @mark_offer.errors.full_messages.join("<br>").html_safe
      redirect_to :action => 'index'
    else
       redirect_to :action => 'index'
    end
  end

  def update
    @mark_offer = KpiMarkOffer.find(params[:id])
      if request.put? and @mark_offer.update_attributes(params[:kpi_mark_offer])
        flash[:notice] = l(:notice_successful_update)
        redirect_to :action => 'index'
        return
      end
    get_marks_for_offer
    render :action => 'edit'
  end

  def create
    @mark_offer = KpiMarkOffer.new(params[:kpi_mark_offer])
    @mark_offer.author_id = User.current.id

    get_marks_for_offer
    if request.post? and @mark_offer.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to :action => 'new'
    else
      render :action => 'new'
    end
  end

  private
  def get_marks_for_offer
    @marks_for_offer = KpiMark.get_mark_for_offer(@mark_offer.user_id) unless @mark_offer.user_id.nil? 
  end
end

app/views/kpi_mark_offers/_form.html.erb
<%= error_messages_for 'mark_offer' %>

<div class="H">
<div class="L">
<div class="L"><%= radio_button_tag'kpi_mark_offer[is_praise]', 1, @mark_offer.is_praise.to_s=='1' %></div> <div class="L"> &nbsp;&mdash;&nbsp; </div> <%= label_tag 'kpi_mark_offer_is_praise_1', l(:praise), :class => 'praise L' %>
</div>
<div class="L"><%= radio_button_tag 'kpi_mark_offer[is_praise]', -1, @mark_offer.is_praise.to_s=='-1' %></div> <div class="L"> &nbsp;&mdash;&nbsp;</div> <%= label_tag 'kpi_mark_offer_is_praise_-1', l(:complain), :class => 'complain L' %>
</div>

<p class="in_col">
<%= f.select(:user_id, (User.active
                            .includes(:user_department).order('lastname').map{|v| ["<nobr>#{v.name} &mdash; #{v.user_department.try(:name)}</nobr>".html_safe, v.id]}), {:label => l(:target_employee), :include_blank => true }, :class => 'select2', :data => {:url => url_for(:controller => 'kpi_marks', :action => 'show_for_offer')}) %>
</p>

<div id="show_for_offer">
  <% unless @mark_offer.user_id.nil? %>
    <%= render :partial => 'kpi_marks/show_for_offer' %>
  <% end %>
</div>

<p class="in_col">   
<%= f.text_area :description, :rows => 8, :class => 'wiki-edit' %>
</p>

<p>
<%= submit_tag l(@mark_offer.new_record? ? :button_create : :button_save) %>
</p>

app/views/kpi_mark_offers/_mark_offer_details.html.erb
<% totals = @mark.get_mark_offer_totals %>

<% is_praise = nil %>
<% i = 0 %>
<% @mark.kpi_mark_offers.includes(:author).order('is_praise, created_at').each_with_index do |offer, k| %>
  <% if is_praise!=offer.is_praise %>
    <% if k > 0 %>
      </table>
    <% end %>
    <div class="<%= offer.is_praise>0 ? 'praise' : 'complain' %>"><big><%= totals[offer.is_praise].abs.to_i %></big> &mdash; <%= offer.is_praise>0 ? l(:praises) : l(:complains) %></div>
    <table class="list">
    <% i = k %>
    <% is_praise = offer.is_praise %>
  <% end %>
  <tr>
    <td><%= format_date offer.created_at %></td>
    <td>
    <%= link_to_user offer.author %>
      <div class="grey">
      <%= offer.description %>
      </div>
    </td>
  </tr>
<% end %>
</table>


app/views/kpi_mark_offers/_show_mark_offer_details.html.erb
asdasdadad

app/views/kpi_mark_offers/edit.html.erb
<h2><%=l(:complain_or_praise)%></h2>

<%= labelled_form_for @mark_offer do |f| %>
<%= render :partial => 'kpi_mark_offers/form', :locals => { :f => f } %>
<% end %>

<%= render :partial => 'kpi/sidebar' %>

app/views/kpi_mark_offers/index.html.erb

<div class="contextual">
</div>

<h2><%=l(:mark_offers)%></h2>

<% if @mark_offers!=[] %>

<table class="list indicators">
<thead>
  <tr>
  <th><%= l(:employee) %></th>
  <th><%= l(:label_mark_period) %></th>  
  <th><%= l(:indicator) %></th>  
  <th></th>
  <th></th>
  </tr>
</thead>

<tbody>
<% @mark_offers.each do |offer| %>
  <tr>
  <td><%= link_to_user offer.user  %></td>
  <td>
    <% unless offer.kpi_mark.nil? %>
    <%= ((format_date offer.kpi_mark.start_date)+" &mdash; "+(format_date offer.kpi_mark.end_date)).html_safe %>
    <% end %>
  </td>
  <td>
    <% unless offer.kpi_mark.nil? %>
    <%= offer.kpi_mark.kpi_period_indicator.indicator.try(:name) %></td>  
    <% end %>
  <td><% if offer.is_praise > 0 %> <%= image_tag 'thumb_up.png', :plugin => :kpi %> <% else %> <%= image_tag 'thumb_down.png', :plugin => :kpi %><% end %></td>
  <td>
      <%= link_to(l(:button_edit), { :controller => 'kpi_mark_offers', :action => 'edit', :id => offer }, :class => 'icon icon-edit') %>

        <%= link_to(l(:button_delete), kpi_mark_offer_path(offer),
                                       :method => :delete,
                                       :confirm => l(:text_are_you_sure),
                                       :class => 'icon icon-del') %>
  </td>
  </tr>
<% end %>
</tbody>

</table>

<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<%= render :partial => 'kpi/sidebar' %>

app/views/kpi_mark_offers/mark_offers.html.erb
<%= render :partial => "kpi_mark_offers/mark_offer_details" %>

app/views/kpi_mark_offers/new.html.erb
<h2><%=l(:complain_or_praise)%></h2>


<%= labelled_form_for @mark_offer do |f| %>
<%= render :partial => 'kpi_mark_offers/form', :locals => { :f => f } %>
<% end %>

<%= render :partial => 'kpi/sidebar' %>