config/routes.rb
RedmineApp::Application.routes.draw do
	resources :indicators
	resources :kpi_patterns

	resources :kpi_mark_offers do
		collection do
			get 'mark_offers/:mark_id', :action => 'mark_offers'
			end
		
		end
	#resources :kpi_calc_periods
	#match 'kpi', :controller => 'kpi', :action => 'index', :via => [:get]
	#match 'kpi/marks', :controller => 'kpi', :action => 'marks', :via => [:get]
	resources :kpi do
		collection do
			#get '/', :action => 'index'
			#get 'marks'
			#get 'marks/:date', :action => 'marks'
			get 'effectiveness'
			#get 'effectiveness/:date', :action => 'effectiveness'
			get 'effectiveness/:user_id', :action => 'effectiveness'
			get 'effectiveness/:date/:user_id', :action => 'effectiveness'

		end
	end

	match 'indicators/:copy_from/copy', :to => 'indicators#new'
	#match 'kpi_patterns/:id/users', :controller => 'kpi_patterns', :action => 'add_users', :id => /\d+/, :via => :post, :as => 'kpi_patters_users'
	#match 'kpi_patterns/:id/users/:user_id', :controller => 'kpi_patterns', :action => 'remove_user', :id => /\d+/, :via => :delete, :as => 'kpi_pattern_user'
	#match 'kpi_patterns/:id/indicators', :controller => 'kpi_patterns', :action => 'add_indicators', :id => /\d+/, :via => :post, :as => 'kpi_patters_indicators'
	#match 'kpi_patterns/:id/update_indicators', :controller => 'kpi_patterns', :action => 'update_indicators', :id => /\d+/, :via => :post, :as => 'kpi_patterns_indicators_edit'
	#match 'kpi_patterns/:id/indicators/:indicator_id', :controller => 'kpi_patterns', :action => 'remove_indicator', :id => /\d+/, :via => :delete, :as => 'kpi_pattern_indicator'
	match 'kpi_patterns/:copy_from/copy', :to => 'kpi_patterns#edit'


	resources :kpi_user_surcharges do
	    member do
	    	get 'show_surcharges', :action => 'show_surcharges'
	    	post 'add_surcharge', :action => 'add_surcharge'
	    end
	end

	resources :kpi_applied_reports do
		collection do
			get 'show', :action => 'show'
			get 'apply/:date/:department_id', :action => 'apply'
			get 'audit/:date/:department_id', :action => 'audit'
			get 'cancel/:date/:department_id', :action => 'cancel'
			get 'cancel_audit/:date/:department_id', :action => 'cancel_audit'
		end

	end

	resources :kpi_period_users do
	    member do
	    	get 'edit_hours', :action => 'edit_hours'
	    	get 'edit_base_salary', :action => 'edit_base_salary'
	    	get 'close_message', :action => 'close_message'
	    	get 'edit_jobprise', :action => 'edit_jobprise'
	    	post 'update_base_salary', :action => 'update_base_salary'
	    	post 'update_jobprise', :action => 'update_jobprise'
	    	post 'update_hours', :action => 'update_hours'
	    	get 'close'
	    	get 'reopen'
	    	get 'reopen_message'
	    end
	end

	resources :kpi_marks do
	    member do
	      get 'edit_plan', :action => 'edit_plan'
	      post 'update_plan', :action => 'update_plan'
	      get 'edit_fact', :action => 'edit_fact'
	      post 'update_fact', :action => 'update_fact'
	      get 'show_info', :action => 'show_info'
	      get 'disable', :action => 'disable'
	      get 'enable', :action => 'enable'
	    end

	    collection do
				#get '/:date', :action => 'index'
	    	get 'user/:user_id', :action => 'user_marks'
	    	post 'update_user_marks/:user_id', :action => 'update_user_marks'
	    	get 'show_for_offer', :action => 'show_for_offer'
	    	#get 'user/:user'
	    end
	end

	resources :kpi_patterns do
	    member do
	      post 'add_users', :action =>'add_users'
	      delete 'remove_user/:user_id', :action => 'remove_user'
	      post 'add_indicators', :action => 'add_indicators'
	      post 'update_indicators', :action => 'update_indicators'
	      delete 'remove_indicator/:indicator_id', :action => 'remove_indicator'
	      get 'autocomplete_for_user'
	      get 'autocomplete_for_indicator'
	    end
	end

	resources :kpi_imported_values do
	    collection do
	      post 'update_values'
	      get 'edit_values'
	      get 'permission_titles', :action => 'permission_titles'
	    end
	end

	resources :kpi_calc_periods do
		collection do
		#get '/:date', :action => 'index'
	    end

	    member do
	   	  # get 'close_for_user/:user_id', :action => 'close_for_user'
	   	  # get 'reopen_for_user/:user_id', :action => 'reopen_for_user'
	      post 'add_inspectors'
	      post 'add_users', :as => 'add_users'
	      get 'autocomplete_for_user'
	      get 'autocomplete_for_applied_user'
	      get 'show_warning_message'
	      get 'activate'
	      get 'close'
	      delete 'remove_inspector/:indicator_inspector_id', :action => 'remove_inspector', :as => 'remove_inspector'
	      delete 'remove_user/:period_user_id', :action => 'remove_user', :as => 'remove_user'
	      post 'update_inspectors', :action => 'update_inspectors', :as => 'update_inspectors'
	      post 'update_plans', :action => 'update_plans', :as => 'update_plans'
	    end
	end

end


# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

app/models/indicator.rb
class Indicator < ActiveRecord::Base
  validates_presence_of :name, :kpi_category_id, :kpi_unit_id, :interpretation
  validates_uniqueness_of :name
  validates_length_of :name, :maximum => 120
  validate :matrix_has_more_two_items, :matrix_should_not_have_empty_values
  before_destroy :pattern_not_exist
 
  serialize :matrix
  serialize :pattern_settings
  serialize :pattern_plan_settings

  belongs_to :kpi_category
  belongs_to :kpi_unit
  belongs_to :kpi_pattern

  has_many :kpi_pattern_indicators
  has_many :kpi_patterns, :through => :kpi_pattern_indicators

  has_many :kpi_period_indicators
  has_many :kpi_calc_periods, :through => :kpi_period_indicators

	scope :not_in_kpi_pattern, lambda {|pattern|
		pattern_id = pattern.is_a?(KpiPattern) ? pattern.id : pattern.to_i
		{ :conditions => ["#{Indicator.table_name}.id NOT IN (SELECT pi.indicator_id FROM kpi_pattern_indicators pi WHERE pi.kpi_pattern_id = ?)", pattern_id] }
		}  

  INTERPRETATION_FACT = 0
  INTERPRETATION_MATRIX = 1

  INPUT_TYPES={'0' => 'direct_input',
               '1' => 'exact_values'}

  FACT_PATTERNS = {
                  '' => 'no_pattern',
                  '1' => 'avg_custom_field_mark_in_current_period',
                  '2' => 'issue_hours_in_current_period',
                  '3' => 'issue_lag_in_current_period',
                  '4' => 'self_and_executors_issues_lag',
                  '5' => 'self_and_executors_issues_avg_custom_field_mark',
                  '6' => 'import_from_other_system',
                  '7' => 'avg_from_unders'
                  }     

  PLAN_PATTERNS = {
                  '' => 'no_pattern',
                  '1' => 'import_from_other_system',
                  '2' => 'time_clocks_in_current_period'
                  } 

  MAX_NUM_IN_PERIOD=5          

  def pattern_not_exist 	
    errors.add(:base, l(:you_can_not_destroy_indicator)) if kpi_pattern_indicators.any?
    errors.blank?
  end

  def to_s
  	name
  end

  def matrix_has_more_two_items
    errors.add(:matrix, l(:have_to_have_more_then_one_item)) if interpretation == Indicator::INTERPRETATION_MATRIX and matrix['value_of_fact'].size<2
  end

  def matrix_should_not_have_empty_values
    errors.add(:matrix, l(:should_not_have_empty_values)) if interpretation == Indicator::INTERPRETATION_MATRIX and (matrix['value_of_fact'].include?("") or matrix['percent'].include?(""))
  end
end

app/controllers/indicators_controller.rb
class IndicatorsController < ApplicationController
	before_filter :authorized_globaly?, :except => [:show]

	before_filter :find_kpi_units, :only => [:new, :edit]
	before_filter :find_categories, :only => [:new, :edit]
	before_filter :find_indicators, :only => [:index]
	before_filter :find_indicator, :only => [:show]

	helper :kpi
	include KpiHelper

	def index
		
	end

	def new
		if !params[:copy_from].nil?
			source_indicator=Indicator.find(params[:copy_from])
		    attributes = source_indicator.attributes.dup.except('id')
		    @indicator = Indicator.new(attributes)
		else
		    @indicator = Indicator.new
		end
	end

	def edit
		@indicator ||= Indicator.find(params[:id])
	end

	def update
	    @indicator = Indicator.find(params[:id])
	    if request.put? and @indicator.update_attributes(params[:indicator])
	      flash[:notice] = l(:notice_successful_update)
	      redirect_to :action => 'index'
	      return
	    end
		find_kpi_units
		find_categories
	    render :action => 'edit'
	end

	def create
	@indicator = Indicator.new(params[:indicator])
	    if request.post? and @indicator.save
		   	flash[:notice] = l(:notice_successful_create)
		    redirect_to :action => 'index'
		else
			find_kpi_units
			find_categories
		    render :action => 'new'

		end
    end

	def destroy
	    @indicator = Indicator.find(params[:id])
	    @indicator.destroy

	    if @indicator.errors.any?
		   flash[:error] = @indicator.errors.full_messages.join("<br>").html_safe
		   redirect_to :action => 'index'
	    else
	       redirect_to :action => 'index'
	    end
	
	end    

	def show

	end

	private
	def find_kpi_units
	 @kpi_units=KpiUnit.order(:name)
	end

	def find_categories
	 @kpi_categories=KpiCategory.order(:name)
	end

	def find_indicators
	 @indicators=Indicator.order(:name)
	end

	def find_indicator
	@indicator = Indicator.find(params[:id])
	end
end

app/helpers/indicators_helper.rb
module IndicatorsHelper
	def get_matrix_row(value_of_fact='', percent='', style='style="display:none;"', title='')
		"<tr>
		<td><input type=\"text\" name=\"indicator[matrix][title][]\" class=\"value_of_fact\" value=\"#{title}\" /></td>
		<td><input type=\"text\" name=\"indicator[matrix][value_of_fact][]\" class=\"value_of_fact\" value=\"#{value_of_fact}\" /></td>
		<td><input type=\"text\" name=\"indicator[matrix][percent][]\" class=\"percent\" value=\"#{percent}\" /></td>
		<td>
		<a href=\"#\" class=\"icon icon-add\">#{l(:label_matrix_row_add)}</a>
		<a href=\"#\" class=\"icon icon-del\" #{style}>#{l(:label_matrix_row_del)}</a>
		</td>
		</tr>".html_safe
	end	

	def get_fact_pattern_options
		Indicator::FACT_PATTERNS.sort_by{|k, v| l(v)}.map{|k,v| [l(v), k]}
	end

	def get_plan_pattern_options
		Indicator::PLAN_PATTERNS.sort_by{|k, v| l(v)}.map{|k,v| [l(v), k]}
	end

	def options_for_role(indicator)
		default = nil

		if not indicator.pattern_settings.nil?
			default = indicator.pattern_settings['role']  if not indicator.pattern_settings['role'].nil?
		end		

		options_for_select(Role.where(:builtin => 0).order(:name).map{ |u| [u.name, u.id]}, default)
	end

	def options_for_indicator(indicator)
		default = nil

		if not indicator.pattern_settings.nil?
			default = indicator.pattern_settings['indicator_id']  if not indicator.pattern_settings['indicator_id'].nil?
		end		

		options_for_select(Indicator.order(:name).map{ |u| [u.name, u.id]}, default)
	end

	def options_for_imported_values(indicator, plan = false)
		default = nil

		pattern_settings = indicator.pattern_settings
		pattern_settings = indicator.pattern_plan_settings if plan

		if not pattern_settings.nil?
			default = pattern_settings['imported_value_id']  if not pattern_settings['imported_value_id'].nil?
		end		

		if plan
			options_for_select(KpiImportedValue.order(:name).where("plan_value_enable", true).map{ |u| [u.name, u.id]}, default)
		else
			options_for_select(KpiImportedValue.order(:name).where("fact_value_enable", true).map{ |u| [u.name, u.id]}, default)
		end
	end

	def options_for_mark_custom_field(indicator)
		default = nil

		if not indicator.pattern_settings.nil?
			default = indicator.pattern_settings['mark_custom_field']  if not indicator.pattern_settings['mark_custom_field'].nil?
		end		

		options_for_select(CustomField.where(:field_format => 'kpi_mark').order(:name).map{ |u| [u.name, u.id]}, default)
	end

	def get_num_on_period
		num=[]
		Indicator::MAX_NUM_IN_PERIOD.times{|i| num[i]=[i+1, i+1]}
		num
	end
end

app/views/indicators/_form.html.erb
<%= error_messages_for 'indicator' %>

<div class="h">
<div class="L left_form_part">
<div class="box tabular">

<p><%= f.text_field :name, :required => true, :label => l(:kpi_indicator_name_label), :style=>'width: 98%;' %></p>
<p><%= f.select :input_type, (Indicator::INPUT_TYPES.map{|k,v| [l("input_type_#{v}"), k]}), :required => true %></p>
<p><%= f.select :kpi_category_id, (@kpi_categories.collect {|p| [p.name, p.id]}), :label => l(:kpi_category_label), :required => true %></p>
<p><%= f.select :kpi_unit_id, (@kpi_units.collect {|p| [p.name, p.id]}), :label => l(:kpi_indicator_unit_label), :required => true %></p>
<p><%= f.select :num_on_period, get_num_on_period, :required => true %></p>
<p><%= f.check_box :objective %></p>
<p>   <%= f.text_area :description,
                   :cols => 60,
                   :rows => (@indicator.description.blank? ? 10 : [[10, @indicator.description.length / 50].max, 70].min),
                   :class => 'wiki-edit',
                   :no_label => true %>
</p>
</div>
</div>

<div class="L right_form_part">
<div class="box tabular">

<fieldset>
<legend><%= l(:editing_fact_pattern) %></legend>
<p><%= f.select :pattern, get_fact_pattern_options, {:label => l(:kpi_fact_pattern), :required => false}, {'data-cf' => 'kpi_pattern_custom_fields', :class => 'patten_sb'} %></p>


<div id="kpi_pattern_custom_fields">
<p class="I kpi_pattern_custom_field_1 kpi_pattern_custom_field_5">
<%= label_tag 'indicator_pattern_settings_mark_custom_field', l(:mark_custom_field) %>
<%= select_tag 'indicator[pattern_settings][mark_custom_field]', options_for_mark_custom_field(@indicator) %>
</p>
<p class="I kpi_pattern_custom_field_5 kpi_pattern_custom_field_4">
<%= label_tag 'indicator_pattern_settings_role', l(:if_has_role) %>
<%= select_tag 'indicator[pattern_settings][role]', options_for_role(@indicator) %>
</p>
<p class="I kpi_pattern_custom_field_6">
<%= label_tag 'indicator_pattern_settings_imported_value_id', l(:imported_value) %>
<%= select_tag 'indicator[pattern_settings][imported_value_id]', options_for_imported_values(@indicator) %>
</p>
<p class="I kpi_pattern_custom_field_7">
<%= label_tag 'indicator_pattern_settings_indicator_id', l(:indicator) %>
<%= select_tag 'indicator[pattern_settings][indicator_id]', options_for_indicator(@indicator) %>
</p>
</div>

</fieldset>

<fieldset>
<legend><%= l(:editing_plan_pattern) %></legend>
<p><%= f.select :pattern_plan, get_plan_pattern_options, {:label => l(:kpi_fact_pattern), :required => false}, {'data-cf' => 'kpi_pattern_plan_custom_fields', :class => 'patten_sb'} %></p>


<div id="kpi_pattern_plan_custom_fields">
<p class="I kpi_pattern_custom_field_1 kpi_pattern_custom_field_2">
<%= label_tag 'indicator_pattern_settings_role', l(:imported_value) %>
<%= select_tag 'indicator[pattern_plan_settings][imported_value_id]', options_for_imported_values(@indicator, true) %>
</p>
<p class="I kpi_pattern_custom_field_1 kpi_pattern_custom_field_2">
<%= label_tag 'indicator_pattern_settings_imported_value_percent', l(:imported_value_percent) %>
<%= text_field_tag 'indicator[pattern_plan_settings][imported_value_percent]', !@indicator.pattern_plan_settings.nil? && !@indicator.pattern_plan_settings['imported_value_percent'].nil? ? @indicator.pattern_plan_settings['imported_value_percent'] : 100, :class => 'weight', :maxlength => 3 %>
</p>

</div>

</fieldset>

<fieldset>
<legend><%= l(:editing_matrix_of_interpretation) %></legend>
<p><%= f.select :interpretation, ([[l("kpi_interpretation_label_#{Indicator::INTERPRETATION_FACT}"), Indicator::INTERPRETATION_FACT],
								  [l("kpi_interpretation_label_#{Indicator::INTERPRETATION_MATRIX}"), Indicator::INTERPRETATION_MATRIX]]),
								  :label => l(:kpi_interpretation_label), :required => true %></p>

<% if @indicator.interpretation.to_s==Indicator::INTERPRETATION_FACT.to_s or @indicator.interpretation.nil? %>
    <% table_style='style="display:none;"'.html_safe %>
    <% abs_int_style='' %>
<% else %>
    <% table_style='' %>
    <% abs_int_style='style="display:none;"'.html_safe %>
<% end %>

<div id="kpi_matrix_div" <%= table_style %>>
<table class="list" id="kpi_matrix">
<tr>
<th><%= l(:indicator_title) %></th>
<th><%= l(:value_of_fact) %></th>
<th><%= l(:percent) %></th>
<th></th>
</tr>

<% if !@indicator.matrix.nil? and !@indicator.matrix['value_of_fact'].nil? %>
	<% style='style="display:none;"'  %>
	<% style='' if @indicator.matrix['value_of_fact'].size>2 %>
	<% @indicator.matrix['value_of_fact'].each do |v| %>
		<% index = @indicator.matrix['value_of_fact'].index(v)  %>
		<% title = @indicator.matrix['title'].nil? ? '' : @indicator.matrix['title'][index] %>
		<%= get_matrix_row(v, @indicator.matrix['percent'][index], style, title) %>
	<% end %>
<% else %>
	<%= get_matrix_row %>
	<%= get_matrix_row %>
<% end %>
</table>

<br/>
<a href="#" id="fill_mark_values"><%= l(:fill_mark) %></a>

<div class="I" id="kpi_mark_values">
<span><div><%= l(:great_mark) %></div><div>150</div><div>150</div></span>
<span><div><%= l(:good_mark) %></div><div>100</div><div>100</div></span>
<span><div><%= l(:satisfactory_mark) %></div><div>50</div><div>50</div></span>
<span><div><%= l(:bad_mark) %></div><div>0</div><div>0</div></span>
<span><div><%= l(:terribly_mark) %></div><div>-50</div><div>-50</div></span>
</div>
</div>


<div id="absolute_interpretation_settings"  <%= abs_int_style %>>
<p><%= f.text_field :max_effectiveness, :required => false, :label => l(:kpi_indicator_max_effectiveness_label), :class => 'weight' %></p>
<p><%= f.text_field :min_effectiveness, :required => false, :label => l(:kpi_indicator_min_effectiveness_label), :class => 'weight' %></p>
</div>

</fieldset>

</div>
</div>

</div>

<div>
<%= submit_tag l(@indicator.new_record? ? :button_create : :button_save) %>
</div>

app/views/indicators/edit.html.erb
<div class="contextual">
<%= render :partial => 'kpi/kpi_common_links' %>
</div>

<h2><%=l(:label_kpi_indicators_edit)%></h2>

<%= labelled_form_for @indicator do |f| %>
<%= render :partial => 'indicators/form', :locals => { :f => f } %>
<% end %>

<%= render :partial => 'kpi/sidebar' %>

app/views/indicators/index.html.erb

<div class="contextual">
<%= render :partial => 'kpi/kpi_common_links' %>
</div>

<h2><%=l(:label_kpi_indicators)%></h2>

<% if @indicators.any? %>

<table class="list indicators">
<thead>
	<tr>
	<th><%= l(:label_kpi_indicators) %></th>
	<th><%= l(:kpi_interpretation_label) %></th>
	<th></th>
	</tr>
</thead>

<tbody>
<% @indicators.each do |indicator| %>
	<tr class="<%= indicator.kpi_category.color %>">
		<td><%= link_to h(indicator.name), edit_indicator_path(indicator) %></td>
		<td><%= l("kpi_interpretation_label_#{indicator.interpretation}") %></td>
		<td class="buttons">
			<%= link_to(l(:button_copy), { :controller => 'indicators', :action => 'new', :copy_from => indicator }, :class => 'icon icon-copy') %>

		    <%= link_to(l(:button_delete), indicator_path(indicator),
		                                   :method => :delete,
		                                   :confirm => l(:text_are_you_sure),
		                                   :class => 'icon icon-del') %>
		</td>
	</tr>
<% end %>
</tbody>

</table>

<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<%= render :partial => 'kpi/sidebar' %>

app/views/indicators/new.html.erb
<h2><%=l(:label_kpi_indicators_new)%></h2>


<%= labelled_form_for @indicator do |f| %>
<%= render :partial => 'indicators/form', :locals => { :f => f } %>
<% end %>

<%= render :partial => 'kpi/sidebar' %>

app/views/indicators/show.html.erb
<h2><%= @indicator.name %></h2>

<div>
	<%= @indicator.description %>
</div>